language: java
jdk:
  oraclejdk11
env:
  - NODE_VERSION=12

script:
  - cd ui/
  - npm install

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key:
    secure: $HEROKU_API_KEY
  app: pragma-dev